import type {Metadata} from 'next'
import '@/app/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import {SpeedInsights} from '@vercel/speed-insights/next'
import {Analytics as VercelAnalytics} from '@vercel/analytics/react'
import YandexMetrika from '~/Global/Analytics'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}

        {process.env.NODE_ENV === 'production' && (
          <>
            <SpeedInsights />
            <VercelAnalytics />
            <YandexMetrika />
          </>
        )}
      </body>
    </html>
  )
}
