import type {Metadata} from 'next'
import localFont from 'next/font/local'
import './globals.css'

import Nav from '@/components/Nav'

const SuisseIntl = localFont({
  src: [
    {
      path: '../assets/fonts/SuisseIntl-Light.woff2',
      weight: '300',
    },
    {
      path: '../assets/fonts/SuisseIntl-Regular.woff2',
      weight: '400',
    },
    {
      path: '../assets/fonts/SuisseIntl-Book.woff2',
      weight: '450',
    },
    {
      path: '../assets/fonts/SuisseIntl-Medium.woff2',
      weight: '500',
    },
    {
      path: '../assets/fonts/SuisseIntl-SemiBold.woff2',
      weight: '600',
    },
    {
      path: '../assets/fonts/SuisseIntl-Bold.woff2',
      weight: '700',
    },
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${SuisseIntl.className} bg-custom-black text-custom-t-gray`}>
        <Nav />
        <div className="relative w-full h-full pl-[16.5rem] sm:pl-0 ">
          <main className="relative max-w-[700px] mx-auto px-5 pt-20 pb-44">{children}</main>
        </div>
      </body>
    </html>
  )
}
